config/routes.rb
Rails.application.routes.draw do


  get 'cart', to: 'cart#show', as: 'cart'
  get 'checkout', to: 'cart#checkout', as: 'checkout'

  root 'cardboards#index'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :cardboards, only: [:index, :show]
  resources :line_items, only: [:create, :update, :destroy]
  resources :users, except: [:index, :new, :create, :edit, :update, :destroy, :show] do
    resources :orders, only: [:index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cardboard.rb
class Cardboard < ApplicationRecord

  has_many :line_items
  has_many :orders, through: :line_items

end

app/models/line_item.rb
class LineItem < ApplicationRecord

  belongs_to :order
  belongs_to :cardboard

  validates :order_id, uniqueness: { scope: :cardboard_id }

  before_save :calc_price

  def calc_price
    self.price = cardboard.price * quantity
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user, optional: true
  has_many :line_items, dependent: :destroy
  has_many :cardboards, through: :line_items

  enum order_status: {'In Progress': 0, 'Completed': 1}

  before_save :price_calculation

  def calc_item_count
    self.item_count = line_items.sum(:quantity)
  end

  def calc_item_total
    self.item_total = line_items.sum(:price)
  end

  def calc_shipment_total
  end

  def calc_promo_total
  end

  def calc_grand_total
    self.grand_total = item_total + shipment_total + promo_total
  end

  def price_calculation
    calc_item_count
    calc_item_total
    calc_shipment_total
    calc_promo_total
    calc_grand_total
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


   has_many :orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      begin
        Order.find(session[:order_id])
      rescue ActiveRecord::RecordNotFound
        Order.new
      end
    else
      Order.new
    end
  end


end

app/controllers/cardboards_controller.rb
class CardboardsController < ApplicationController
  before_action :set_cardboard, only: [:show, :edit, :update, :destroy]

  # GET /cardboards
  # GET /cardboards.json
  def index
    @cardboards = Cardboard.all.map{|cardboard| cardboard.attributes.merge(url: cardboard_path(cardboard.id))}
  end

  # GET /cardboards/1
  # GET /cardboards/1.json
  def show
  end

  # GET /cardboards/new
  def new
    @cardboard = Cardboard.new
  end

  # GET /cardboards/1/edit
  def edit
  end

  # POST /cardboards
  # POST /cardboards.json
  def create
    @cardboard = Cardboard.new(cardboard_params)

    respond_to do |format|
      if @cardboard.save
        format.html { redirect_to @cardboard, notice: 'Cardboard was successfully created.' }
        format.json { render :show, status: :created, location: @cardboard }
      else
        format.html { render :new }
        format.json { render json: @cardboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cardboards/1
  # PATCH/PUT /cardboards/1.json
  def update
    respond_to do |format|
      if @cardboard.update(cardboard_params)
        format.html { redirect_to @cardboard, notice: 'Cardboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @cardboard }
      else
        format.html { render :edit }
        format.json { render json: @cardboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cardboards/1
  # DELETE /cardboards/1.json
  def destroy
    @cardboard.destroy
    respond_to do |format|
      format.html { redirect_to cardboards_url, notice: 'Cardboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cardboard
      @cardboard = Cardboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cardboard_params
      params.require(:cardboard).permit(:cardboard_type, :price)
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_action :authenticate_user!, only: [:checkout, :payment]

  def show
    @line_items = current_order.line_items.map{|line_item| line_item.attributes.merge(
      {
        cardboard_type: line_item.cardboard.cardboard_type,
        cardboard_price: line_item.cardboard.price
      }
    )}
  end

  def checkout
    @order = current_order
    @order.attributes = {user_id: current_user.id, order_status: 'Completed'}
    if @order.save
      session[:order_id] = nil
      redirect_to user_order_path(user_id: current_user,id: @order), success: 'Order was successfully placed'
    else
      redirect_back fallback_location: checkout_path, error: error_message
    end
  end

  def payment
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  before_action :set_line_item, only: [:update, :destroy]

  def create
    @order = current_order
    @line_item = @order.line_items.find_or_initialize_by(cardboard_id: line_item_params[:cardboard_id])
    @line_item.quantity += line_item_params[:quantity].to_i
    if @line_item.save
      @order.save
      session[:order_id] = @order.id
    else

    end
  end

  def update
  end

  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_url, notice: 'Item was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private

  def line_item_params
    params.require(:line_item).permit(:quantity, :cardboard_id)
  end

  def set_line_item
    @line_item = LineItem.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show]

  before_action :authenticate_user!
  before_action :current_user_only

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where(order_status: 1)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @line_items = @order.line_items
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {})
    end

    def current_user_only
      if params[:user_id] != current_user.id
        redirect_back fallback_location: '/', notice: 'You are not allowed to perform this action.'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
      case level
          when :notice then "alert alert-info"
          when :success then "alert alert-success"
          when :error then "alert alert-danger"
          when :alert then "alert alert-warning"
      end
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "#{flash_class(msg_type.to_sym)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end

  def error_message
    'I\'m sorry, we are currently experiencing system problems and are unable to process your request. Please try again later'
  end
end

app/helpers/cardboards_helper.rb
module CardboardsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/cardboards/_form.html.erb
<%= form_with(model: cardboard, local: true) do |form| %>
  <% if cardboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cardboard.errors.count, "error") %> prohibited this cardboard from being saved:</h2>

      <ul>
      <% cardboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cardboard_type %>
    <%= form.text_field :cardboard_type, id: :cardboard_cardboard_type %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :cardboard_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cardboards/edit.html.erb
<h1>Editing Cardboard</h1>

<%= render 'form', cardboard: @cardboard %>

<%= link_to 'Show', @cardboard %> |
<%= link_to 'Back', cardboards_path %>

app/views/cardboards/index.html.erb
<%= react_component("Cardboards", cardboards: @cardboards) %>

app/views/cardboards/new.html.erb
<h1>New Cardboard</h1>

<%= render 'form', cardboard: @cardboard %>

<%= link_to 'Back', cardboards_path %>

app/views/cardboards/show.html.erb
<%= react_component('CardboardShow', @cardboard) %>

app/views/cart/checkout.html.erb
<h1>Cart#checkout</h1>
<p>Find me in app/views/cart/checkout.html.erb</p>

app/views/cart/show.html.erb
<%= react_component 'Cart', line_items: @line_items, current_order: current_order%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Captur3dChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
      <%= react_component 'Navbar', current_order: current_order %>
      <main class='container'>
        <%= flash_messages %>
        <%= yield %>
      </main>

  </body>
</html>

app/views/orders/index.html.erb
<h1>Your Orders</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Order number</th>
      <th>No. of Items</th>
      <th>Total</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <th>#<%=order.id%></th>
        <th><%=order.item_count%></th>
        <th><%=order.grand_total%></th>
        <td><%= link_to 'Show', user_order_path(user_id: current_user, id: order) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/show.html.erb
<h1>Order #<%=@order.id%></h1>
<table class='table cart-line-item-list'>
  <thead>
    <tr>
      <th>Cardboard Type</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <%@line_items.each do |line_item|%>
      <td><%=line_item.cardboard.cardboard_type%></td>
      <td><%=line_item.quantity%></td>
      <td><%=line_item.cardboard.price%></td>
    <%end%>
  </tbody>
</table>
<div class='cart-meta'>
  <div>
    <span class='cart-meta-text'>Subtotal</span>
    <span class='cart-meta-number'><%=@order.item_total%></span>
  </div>
  <div>
    <span class='cart-meta-text'>Discount</span>
    <span class='cart-meta-number'><%=@order.promo_total%></span>
  </div>
  <div>
    <span class='cart-meta-text'>Shipping Fee</span>
    <span class='cart-meta-number'><%=@order.shipment_total%></span>
  </div>
  <div>
    <span class='cart-meta-text'>Total</span>
    <span class='cart-meta-number'><%=@order.grand_total%></span>
  </div>
</div>
<span class='clear'></span>